version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db-data: